 module.exports= domainsList = `*.amazon.co.uk 89
    *.doubleclick.net 139
    *.fbcdn.net 212
    *.in-addr.arpa 384
    *.l.google.com 317
    1.client-channel.google.com 110
    6.client-channel.google.com 45
    a.root-servers.net 1059
    apis.google.com 43
    clients4.google.com 71
    clients6.google.com 81
    connect.facebook.net 68
    edgemqtt.facebook.com 56
    graph.facebook.com 150
    mail.google.com 128
    mqttmini.facebook.com 47
    ssl.google-analytics.com 398
    star-mini.c10r.facebook.com 46
    staticxx.facebook.com 48
    www.facebook.com 178
    www.google.com 162
    www.googleanalytics.com 127`;
